[package]
name = "cache-action"
version = "0.0.12"
edition = "2024"

[features]
noop-cache = []
sub60-cache = []

[dependencies]
async-compat = "0.2"
bytes = "1"
clap = { version = "4.5.38", features = ["derive"] }
either = "1"
flume = { version = "0.12" }
futures = { version = "0.3" }
memchr = "2"
nix = { version = "0.31", features = ["process"] }
nix-compat = { git = "https://git.snix.dev/snix/snix", default-features = false, features = [
  "async",
  "wire",
] }
nix-types = { git = "ssh://git@github.com/sub60/nix-types.git" }
nixb = { git = "https://github.com/noib3/nixb", branch = "store-path-info", features = [
  "nix-2-35",
  "store",
] }
pin-project-lite = "0.2"
reqwest = { version = "0.13", features = ["stream"] }
sha2 = "0.11"
smallvec = "1"
smol_str = "0.3.6"
tokio = { version = "1", default-features = false, features = [
  "fs",
  "io-std",
  "io-util",
  "net",
  "rt-multi-thread",
] }
tokio-util = { version = "0.7", features = ["io"] }
url = "2"

[build-dependencies]
pkg-config = "0.3"

[lints.rust]
refining_impl_trait = { level = "allow", priority = -1 }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = "symbols"
