[package]
name = "cache-action"
version = "0.0.8"
edition = "2024"

[dependencies]
async-compat = "0.2"
bytes = "1"
clap = { version = "4.5.38", features = ["derive"] }
either = "1"
flume = { version = "0.12" }
futures = { version = "0.3" }
memchr = "2"
nix = { version = "0.31", features = ["process"] }
nix-types = { git = "ssh://git@github.com/sub60/nix-types.git" }
pin-project-lite = "0.2"
smol_str = "0.3.6"
tokio = { version = "1", default-features = false, features = [
  "io-std",
  "io-util",
  "net",
  "rt-multi-thread",
] }
