name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_version: 2.29.2
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.NIX_TYPES_DEPLOY_KEY }}
      - name: Run Clippy
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true
        run: |
          nix develop .#default -c \
            cargo clippy --workspace --all-features --all-targets --no-deps -- -D warnings

  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_version: 2.29.2
      - name: Check formatting
        run: nix run .#check-formatting
